name: first

on:
    push:
        branches: [ "main" ]

    pull_request:
        branches: [ "main" ]

    workflow_dispatch:

jobs:
    Ubuntu:
        runs-on: ubuntu-latest
        steps:
            - name: Step one - Add Actions
              uses: actions/checkout@v4
            - name: Step two - List Env Variables
              run: env | sort

    Windows:
        runs-on: windows-latest
        steps:
            - name: Step one - Add Actions
              uses: actions/checkout@v4
            - name: Step two - List Env Variables
              run: "Get-ChildItem Env: | Sort-Object Name"

    Mac:
        runs-on: macos-latest
        steps:
            - name: Step one - Add Actions
              uses: actions/checkout@v4
            - name: Step two - List Env Variables
              run: env | sort

    depends:
        needs: [Ubuntu, Windows, Mac]
        runs-on: macos-latest
        steps:
            - name: Completed Date and Time
              run: date

